// Fixed catalog of barber specialization ids. The profile screen only lets a
// master pick from this list (not freeform text) since clients browse/filter
// masters by specialization on the mobile side — unconstrained text would
// make that unusable. Labels are localized via the "Specializations" i18n
// namespace (src/i18n/messages/*/Specializations.json), keyed by these ids.
export const SPECIALIZATION_IDS: string[] = [
  // Core Haircut Styles
  "classic-barber-cut",
  "fade-low",
  "fade-mid",
  "fade-high",
  "fade-skin-bald",
  "fade-drop",
  "fade-burst",
  "fade-temple",
  "taper-low",
  "taper-mid",
  "taper-high",
  "undercut",
  "buzz-cut",
  "crew-cut",
  "ivy-league-cut",
  "pompadour",
  "quiff",
  "slick-back",
  "comb-over",
  "side-part",
  "textured-crop",
  "mullet",
  "mohawk",
  "flat-top",
  "caesar-cut",
  "spiky-cut",
  "layered-cut",
  "curly-afro-cutting",
  "kids-haircuts",

  // Regional & Ethnic Styles (Worldwide)
  "kr-regent",
  "kr-sports-cut",
  "kr-crop-cut",
  "kr-edge-cut",
  "kr-guyle-cut",
  "kr-wolf-cut",
  "kr-down-perm",
  "kr-setting-perm",
  "kr-volume-magic",
  "kr-hippy-perm",
  "jp-mash-cut",
  "jp-wolf-cut",
  "jp-two-block-cut",
  "tr-shave",
  "tr-ear-nose-waxing",
  "tr-fade",
  "af-360-waves",
  "af-box-braids",
  "af-bald-fade-design",
  "af-shape-up",
  "af-locs-retwist",
  "la-taper-fade",
  "la-pompadour",
  "sa-traditional-indian",
  "sa-champi",
  "eu-ivy-league",
  "eu-british-crop",
  "eu-traditional-english",

  // Beard & Facial Hair
  "beard-trim-shaping",
  "beard-sculpting",
  "straight-razor-shave",
  "hot-towel-shave",
  "traditional-turkish-shave",
  "mustache-styling",
  "beard-coloring",
  "beard-lineup",
  "full-beard-package",
  "stubble-styling",

  // Coloring & Chemical Services
  "hair-coloring-full-dye",
  "highlights-lowlights",
  "balayage-ombre",
  "bleaching",
  "gray-coverage",
  "perming",
  "hair-relaxing-straightening",
  "hair-botox-filler",
  "color-correction",

  // Hair Design & Artistic Services
  "hair-tattoo-line-art",
  "braiding",
  "dreadlocks-locs",
  "twist-styles",
  "weaving-extensions",
  "wig-fitting-styling",
  "updos-event-styling",

  // Scalp & Hair Treatments
  "scalp-treatment-exfoliation",
  "scalp-massage-champi",
  "hair-loss-treatment",
  "deep-conditioning",
  "dandruff-treatment",
  "keratin-treatment",
  "protein-treatment",

  // Grooming & Additional Services
  "eyebrow-shaping",
  "ear-waxing-candling",
  "nose-waxing",
  "face-waxing",
  "mens-facial",
  "makeup",
  "nail-care",

  // Specialty/Niche Roles
  "bridal-event-stylist",
  "wig-specialist",
  "extensions-specialist",
  "color-specialist",
  "texture-specialist",
  "mens-grooming-specialist",
  "kids-barber-specialist",
  "master-barber",
];
